"""empty message

Revision ID: fa31d5050724
Revises: 
Create Date: 2024-11-08 17:09:01.924005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa31d5050724'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dados_empenhos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uo', sa.String(length=32), nullable=False),
    sa.Column('ue', sa.String(length=32), nullable=False),
    sa.Column('ano', sa.String(length=32), nullable=False),
    sa.Column('empenho', sa.String(length=32), nullable=False),
    sa.Column('projeto_atividade', sa.String(length=32), nullable=False),
    sa.Column('gmi_fp', sa.String(length=32), nullable=False),
    sa.Column('elemento_item', sa.String(length=32), nullable=False),
    sa.Column('razao_social_credor', sa.String(length=255), nullable=False),
    sa.Column('cnpj_cpf_credor', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dados_empenhos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dados_empenhos_ano'), ['ano'], unique=False)
        batch_op.create_index(batch_op.f('ix_dados_empenhos_cnpj_cpf_credor'), ['cnpj_cpf_credor'], unique=False)
        batch_op.create_index(batch_op.f('ix_dados_empenhos_empenho'), ['empenho'], unique=False)
        batch_op.create_index(batch_op.f('ix_dados_empenhos_gmi_fp'), ['gmi_fp'], unique=False)
        batch_op.create_index(batch_op.f('ix_dados_empenhos_razao_social_credor'), ['razao_social_credor'], unique=False)
        batch_op.create_index(batch_op.f('ix_dados_empenhos_ue'), ['ue'], unique=False)
        batch_op.create_index(batch_op.f('ix_dados_empenhos_uo'), ['uo'], unique=False)

    op.create_table('ordenador_despesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('masp', sa.String(length=32), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('masp'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('dados_nfs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processo_sei', sa.String(length=32), nullable=False),
    sa.Column('doc_sei_nf', sa.String(length=32), nullable=False),
    sa.Column('doc_sei_ateste', sa.String(length=32), nullable=False),
    sa.Column('doc_sei_conformidade', sa.String(length=32), nullable=False),
    sa.Column('numero_nf', sa.String(length=32), nullable=False),
    sa.Column('data_emissao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_entrada', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_vencimento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_inicio_competencia', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_fim_competencia', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observacoes', sa.String(length=255), nullable=False),
    sa.Column('municipio', sa.String(length=255), nullable=False),
    sa.Column('valor_nf', sa.Float(), nullable=False),
    sa.Column('ue', sa.String(length=32), nullable=False),
    sa.Column('ano', sa.String(length=32), nullable=False),
    sa.Column('empenho', sa.String(length=32), nullable=False),
    sa.Column('conformidade', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('banco', sa.String(length=32), nullable=False),
    sa.Column('agencia', sa.String(length=32), nullable=False),
    sa.Column('conta', sa.String(length=32), nullable=False),
    sa.Column('masp', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['masp'], ['ordenador_despesas.masp'], ),
    sa.ForeignKeyConstraint(['ue', 'ano', 'empenho'], ['dados_empenhos.ue', 'dados_empenhos.ano', 'dados_empenhos.empenho'], name='dados_empenho_fk'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dados_nfs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dados_nfs_agencia'), ['agencia'], unique=False)
        batch_op.create_index(batch_op.f('ix_dados_nfs_ano'), ['ano'], unique=False)
        batch_op.create_index(batch_op.f('ix_dados_nfs_banco'), ['banco'], unique=False)
        batch_op.create_index(batch_op.f('ix_dados_nfs_conformidade'), ['conformidade'], unique=False)
        batch_op.create_index(batch_op.f('ix_dados_nfs_conta'), ['conta'], unique=False)
        batch_op.create_index(batch_op.f('ix_dados_nfs_doc_sei_ateste'), ['doc_sei_ateste'], unique=False)
        batch_op.create_index(batch_op.f('ix_dados_nfs_doc_sei_conformidade'), ['doc_sei_conformidade'], unique=False)
        batch_op.create_index(batch_op.f('ix_dados_nfs_doc_sei_nf'), ['doc_sei_nf'], unique=False)
        batch_op.create_index(batch_op.f('ix_dados_nfs_empenho'), ['empenho'], unique=False)
        batch_op.create_index(batch_op.f('ix_dados_nfs_masp'), ['masp'], unique=False)
        batch_op.create_index(batch_op.f('ix_dados_nfs_numero_nf'), ['numero_nf'], unique=False)
        batch_op.create_index(batch_op.f('ix_dados_nfs_processo_sei'), ['processo_sei'], unique=False)
        batch_op.create_index(batch_op.f('ix_dados_nfs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_dados_nfs_ue'), ['ue'], unique=False)

    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_user_id'))
        batch_op.drop_index(batch_op.f('ix_post_timestamp'))

    op.drop_table('post')
    with op.batch_alter_table('dados_nfs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dados_nfs_ue'))
        batch_op.drop_index(batch_op.f('ix_dados_nfs_status'))
        batch_op.drop_index(batch_op.f('ix_dados_nfs_processo_sei'))
        batch_op.drop_index(batch_op.f('ix_dados_nfs_numero_nf'))
        batch_op.drop_index(batch_op.f('ix_dados_nfs_masp'))
        batch_op.drop_index(batch_op.f('ix_dados_nfs_empenho'))
        batch_op.drop_index(batch_op.f('ix_dados_nfs_doc_sei_nf'))
        batch_op.drop_index(batch_op.f('ix_dados_nfs_doc_sei_conformidade'))
        batch_op.drop_index(batch_op.f('ix_dados_nfs_doc_sei_ateste'))
        batch_op.drop_index(batch_op.f('ix_dados_nfs_conta'))
        batch_op.drop_index(batch_op.f('ix_dados_nfs_conformidade'))
        batch_op.drop_index(batch_op.f('ix_dados_nfs_banco'))
        batch_op.drop_index(batch_op.f('ix_dados_nfs_ano'))
        batch_op.drop_index(batch_op.f('ix_dados_nfs_agencia'))

    op.drop_table('dados_nfs')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('ordenador_despesas')
    with op.batch_alter_table('dados_empenhos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dados_empenhos_uo'))
        batch_op.drop_index(batch_op.f('ix_dados_empenhos_ue'))
        batch_op.drop_index(batch_op.f('ix_dados_empenhos_razao_social_credor'))
        batch_op.drop_index(batch_op.f('ix_dados_empenhos_gmi_fp'))
        batch_op.drop_index(batch_op.f('ix_dados_empenhos_empenho'))
        batch_op.drop_index(batch_op.f('ix_dados_empenhos_cnpj_cpf_credor'))
        batch_op.drop_index(batch_op.f('ix_dados_empenhos_ano'))

    op.drop_table('dados_empenhos')
    # ### end Alembic commands ###
